#!/bin/bash

set -e

rm_ldconfig() {
    rm -f /etc/OpenCL/vendors/amdocl64.icd
    rm -f /etc/ld.so.conf.d/x86_64-rocm-opencl.conf && ldconfig
}

case "$1" in
   remove)
       rm_ldconfig
   ;;
   purge)
   ;;
   *)
       exit 0
   ;;
esac

