# rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#ARCH:         x86_64
BuildArch:     x86_64
Name:          rocm-opencl-devel
Version:       1.2.0
Release:       ROCM_OPENCL_PKG_VER
License:       unknown 
Group:         unknown
Summary:       OpenCL/ROCm

Source: %{expand:%%(pwd)}
BuildRoot: %{expand:%%(pwd)}



Vendor:        AMD






Prefix:        ROCM_OUTPUT_DIR/opencl
Provides:      rocm-opencl-devel  
Provides:      rocm-opencl-devel = 1.2.0-ROCM_OPENCL_PKG_VER
Provides:      rocm-opencl-devel(x86-64) = 1.2.0-ROCM_OPENCL_PKG_VER
Requires:      rocm-opencl  
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#Requires:      rpmlib(FileDigests) <= 4.6.0-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1
#Requires:      rpmlib(PayloadIsXz) <= 5.2-1
#suggest
#enhance
%description
DESCRIPTION
===========

%prep
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT
cd $RPM_BUILD_ROOT
cp -R %{SOURCEURL0}/* .

%clean
rm -r -f "$RPM_BUILD_ROOT"

%files
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/include/CL/cl.h"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/include/CL/cl.hpp"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/include/CL/cl_ext.h"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/include/CL/cl_gl.h"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/include/CL/cl_gl_ext.h"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/include/CL/cl_platform.h"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/include/CL/opencl.h"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/include/opencl-c.h"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/hip.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/irif.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/ockl.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_correctly_rounded_sqrt_off.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_correctly_rounded_sqrt_on.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_daz_opt_off.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_daz_opt_on.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_finite_only_off.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_finite_only_on.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_isa_version_700.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_isa_version_701.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_isa_version_702.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_isa_version_801.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_isa_version_802.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_isa_version_803.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_isa_version_810.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_isa_version_900.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_isa_version_902.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_isa_version_904.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_isa_version_906.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_unsafe_math_off.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/oclc_unsafe_math_on.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/ocml.amdgcn.bc"
%attr(0644, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/bitcode/opencl.amdgcn.bc"
%attr(0777, root, root) "ROCM_OUTPUT_DIR/opencl/lib/x86_64/libOpenCL.so"
%changelog
* Sun Nov 06 2016 Laurent Morichetti -  1.0
Initial

